// Auto-generated by tools/bmp_to_header.py.
// DO NOT EDIT BY HAND.

#pragma once

#include <stdint.h>

#include "backgrounds/bitmap_bg.h"

#include "bitmaps/starfield.h"

struct ImageEntry {
  const char*           name;
  const uint16_t*       palette;
  const uint8_t*        pixels;
  const BitmapBg::Region* regions;
  uint8_t               region_count;
};

inline constexpr ImageEntry kImageRegistry[] = {
  { "starfield", kStarfieldPalette, kStarfieldPixels, kStarfieldRegions, kStarfieldRegionsCount },
};

inline constexpr int kImageRegistryCount = 1;
