// Auto-generated by tools/bmp_to_header.py.
// DO NOT EDIT BY HAND.

#pragma once

#include <stdint.h>

#include "backgrounds/bitmap_bg.h"

#include "bitmaps/iss.h"
#include "bitmaps/jupiter.h"
#include "bitmaps/moon.h"
#include "bitmaps/observatory.h"
#include "bitmaps/starfield.h"

struct ImageEntry {
  const char*           name;
  const uint16_t*       palette;
  const uint8_t*        pixels;
  const BitmapBg::Region* regions;
  uint8_t               region_count;
};

inline constexpr ImageEntry kImageRegistry[] = {
  { "iss", kIssPalette, kIssPixels, kIssRegions, kIssRegionsCount },
  { "jupiter", kJupiterPalette, kJupiterPixels, kJupiterRegions, kJupiterRegionsCount },
  { "moon", kMoonPalette, kMoonPixels, kMoonRegions, kMoonRegionsCount },
  { "observatory", kObservatoryPalette, kObservatoryPixels, kObservatoryRegions, kObservatoryRegionsCount },
  { "starfield", kStarfieldPalette, kStarfieldPixels, kStarfieldRegions, kStarfieldRegionsCount },
};

inline constexpr int kImageRegistryCount = 5;
