// Palette-indexed image background.
//
// Like BitmapBg, but the palette + pixels + region table all live in
// flash (generated by tools/bmp_to_header.py from assets/*.bmp), and
// this class just holds three pointers — no 2 KB pixel copy in RAM.
//
// Pixel encoding (mirrors BitmapBg):
//   index <  192  -> entry in this image's per-image 192-entry palette.
//                    Animated by the per-region cyclic shift.
//   index >= 192  -> NOT ALLOWED here. The bmp_to_header.py converter
//                    rejects images that reference indices >= 192,
//                    matching the BG-region-only constraint of the
//                    palette layout (color_palette.h §192/64 split).
//
// One ImagePaletteBg instance can be re-pointed at a different image
// at runtime via set(), so a future "image_id" MQTT field can switch
// images without touching the dispatcher.

#pragma once

#include <stdint.h>

#include <Adafruit_Protomatter.h>

#include "backgrounds/bitmap_bg.h"   // for BitmapBg::Region
#include "config.h"

class ImagePaletteBg {
public:
  // Point at the flash-resident tables for one image. nullptr palette
  // or pixels => render black (defensive default when no images exist).
  void set(const uint16_t* palette,
           const uint8_t*  pixels,
           const BitmapBg::Region* regions,
           uint8_t region_count) {
    m_palette      = palette;
    m_pixels       = pixels;
    m_regions      = regions;
    m_region_count = region_count;
  }

  void render(Adafruit_Protomatter& matrix, uint32_t now_ms) {
    if (m_palette == nullptr || m_pixels == nullptr) {
      matrix.fillScreen(0x0000);
      return;
    }

    // Per-frame shift table (max 4 regions). Same wrap-safe math as
    // BitmapBg — single divide per region, none per pixel.
    static constexpr int MAX_REGIONS = 4;
    uint8_t shifts[MAX_REGIONS] = {0};
    const uint8_t rc =
        m_region_count > MAX_REGIONS ? MAX_REGIONS : m_region_count;
    for (uint8_t r = 0; r < rc; ++r) {
      const BitmapBg::Region& reg = m_regions[r];
      if (reg.length == 0) continue;
      int32_t s = (static_cast<int32_t>(now_ms) * reg.speed) / 1000;
      int32_t m = s % reg.length;
      if (m < 0) m += reg.length;
      shifts[r] = static_cast<uint8_t>(m);
    }

    for (int y = 0; y < PANEL_HEIGHT; ++y) {
      const uint8_t* row = m_pixels + y * PANEL_WIDTH;
      for (int x = 0; x < PANEL_WIDTH; ++x) {
        const uint8_t b = row[x];
        // Look up the region this index falls into and apply its shift.
        uint8_t cycled = b;
        for (uint8_t r = 0; r < rc; ++r) {
          const BitmapBg::Region& reg = m_regions[r];
          if (b >= reg.start && b < reg.start + reg.length) {
            const uint8_t local = static_cast<uint8_t>(b - reg.start);
            const uint8_t rotated =
                static_cast<uint8_t>((local + shifts[r]) % reg.length);
            cycled = static_cast<uint8_t>(reg.start + rotated);
            break;
          }
        }
        matrix.drawPixel(x, y, m_palette[cycled]);
      }
    }
  }

private:
  const uint16_t*         m_palette      = nullptr;
  const uint8_t*          m_pixels       = nullptr;
  const BitmapBg::Region* m_regions      = nullptr;
  uint8_t                 m_region_count = 0;
};
