// observatory/constellation — Director-pushed selector for the
// `constellation_now` scene (planned phase 7.4).
//
// Design contract (mirrors moon/iss/jupiter): HA picks WHICH
// constellation should render right now — typically the one currently
// overhead given (date, observer lat/lon) — and the firmware just
// looks it up in the static catalog (`include/stars.h`, generated by
// `tools/skyculture_to_header.py` from the Stellarium western sky
// culture) and renders it. HA does no observer-frame computation
// per FR-14; firmware does no catalog math. The selector is just an
// integer index into `constellations_iau::kCatalog[]` (88 IAU
// entries, sorted by IAU 3-letter code).
//
// Wire fields:
//   index           — required, 0..kCatalogCount-1 (88 entries),
//                     picks the IAU constellation
//   highlight_star  — optional, 0..63, picks which star within the
//                     constellation gets the "tonight's featured
//                     star" treatment (red blinking + cross). The
//                     index is the BRIGHTNESS RANK among stars
//                     drawn for this constellation: 0 = brightest
//                     (alpha-ish), 1 = second-brightest, etc. This
//                     is independent of HIP numbers so HA can issue
//                     a stable command without catalog details.
//                     Use -1 (or omit) for no highlight.
//
// Cross-core: writer is Core 0 (MQTT callback), reader is Core 1
// (render). Multi-field state → real mutex_t per CODING_PRACTICES §3.
//
// Freshness window: 24 h. The "constellation overhead right now"
// changes ~once an hour, so even a half-day-stale snapshot is still
// pointing at a nearby constellation. The scene's local fallback (a
// slow rotation through the catalog every 30 s) takes over past that.
//
// (added in phase 7.4 prep)

#pragma once

#include <stdint.h>

namespace constellation_state {

struct Snapshot {
  bool    valid;            // false until first set_from_mqtt OR stale
  uint8_t index;            // 0..kCatalogCount-1
  bool    have_highlight;   // false → no star highlighted
  uint8_t highlight_star;   // 0..15, index into the entry's stars[]
  uint32_t set_at_ms;
};

constexpr uint32_t kFreshMs = 24u * 60u * 60u * 1000u;  // 24 h

// One-time mutex init. Call from setup() before either core spins.
void init();

// MQTT writer. Range-checking happens in mqtt_link before this call.
void set_from_mqtt(uint8_t index,
                   bool have_highlight, uint8_t highlight_star,
                   uint32_t now_ms);

// Reader. Returns true with a fresh snapshot if a value has been
// pushed in the last kFreshMs; false otherwise (caller falls back to
// the local rotation).
bool get(uint32_t now_ms, Snapshot* out);

}  // namespace constellation_state
